language: php

services:
    - postgresql

php:
    - 7.2
    - 7.3

env:
    - DB_TYPE=pgsql DB_HOST=localhost DB_NAME=userdevice DB_PORT=5432 DB_USERNAME=postgres DB_PASSWORD=root

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source
    - psql -c 'CREATE DATABASE userdevice;'

script:
    - ./vendor/bin/phpcs --standard=PSR2 ./src ./tests
    - ./vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)
